---
name: LiamxDevMCPanel-API
version: 3.0.0
api: [2.0.0, 3.0.0]
main: LiamxDevMCPanel\Main
authors: [Fenek912, LiamxDev]
description: API for getting info from MCPE servers
website: https://github.com/Fenek912/LiamxDevMCPanel-API
...
